name: Checking out the Lint and Format errors
on:
  push:
    branches:
      -"*"
  pull_request:
    branches:
      -"*"
jobs:
  Checking-lint-and-Format:
    runs-on: Ubuntu-latest
    steps:
      - name: Cloning the github repository
        uses: actions/checkout@v4
      - name: Installing bun
        uses: oven-sh/setup-bun@v2
      - name: installing dependencies
        run: bun install
      - name: Lint check
        run: bun lint
      - name: Format Check
        run: bun Format